# boards are ordered by priority so that when monitoring a build developers get feedback on the important ones first.
matrix:
#Do not define 'global' env vars here.  They cannot be used with API builds
    fast_finish: true
    include:
      - if: type = cron
        env:
          MAKETARGET="zips winzips"
      - if: type != cron
        env:
          MAKETARGET=lint
          MAKETARGET=zip_devo8

dist: trusty

language: minimal

git:
  depth: 5

script: 
  - |
    echo $MAKETARGET
